baseurl = "https://statimatics.rbind.io/"
relativeurls = true
languageCode = "en-us"
title = "Adventures in Data Science"
theme = "hugo-lithium-theme"
googleAnalytics = "UA-103837477-1"
disqusShortname = "statimatics"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Vitae"
    url = "/vitae/"  
[[menu.main]]
    name = "Facebook"
    url = "https://facebook.com/statimatics"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/mts4955"

[params]
    description = "A journal of my adventures in data science"
    footer = "&copy; [Oluwasegun Ojo](/) 2016 - 2018 | [Github](https://github.com/statimatics) | [Twitter](https://twitter.com/mts4955)"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
    
    

